server.port=8080
spring.application.name=alarm-processor
spring.config.import=configserver:http://config-server:8888
spring.kafka.consumer.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=nms-alarm-group
spring.kafka.properties.schema.registry.url=http://schema-registry:8081
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
# Tell the Avro decoder to automatically map incoming records straight to our compiled target class structures
spring.kafka.properties.specific.avro.reader=true
spring.kafka.properties.spring.json.trusted.packages="com.telecom.nms.*"
# Setting a transaction prefix instantly enables Spring's KafkaTransactionManager
spring.kafka.producer.transaction-id-prefix=tx-alarm-proc-

# Enforce that messages must be replicated across brokers before confirming safe write
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.properties.auto.register.schemas=true