package com.telecom.nms.alarm.consumer;

import com.telecom.nms.alarm.model.AlarmTelemetryAvro; // 🚀 Your autogenerated Avro class
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Component;
import java.util.Map;

@Component
public class TelemetryIngestionBridge {

    private static final Logger log = LoggerFactory.getLogger(TelemetryIngestionBridge.class);
    private final KafkaTemplate<String, Object> kafkaTemplate;
    private static final String PROD_TOPIC = "telecom-network-alarms";

    public TelemetryIngestionBridge(KafkaTemplate<String, Object> kafkaTemplate) {
        this.kafkaTemplate = kafkaTemplate;
    }

    // 📥 Intercept the unvalidated text maps coming out of your gateway container
    @KafkaListener(
    topics = "telecom-raw-telemetry", 
    groupId = "nms-bridge-group",
    properties = {
        "spring.json.value.default.type=java.util.Map",
        "spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer"
    }
)
    public void processRawTelemetry(Map<String, Object> rawPayload) {
        log.info("📥 Ingestion Bridge: Captured raw payload map from gateway entry lane.");

        String equipmentId = (String) rawPayload.getOrDefault("equipmentId", "GENERIC_NODE");
        String severity = (String) rawPayload.getOrDefault("severity", "WARNING");
        String problem = (String) rawPayload.getOrDefault("problem", "Unhandled alerting telemetry");
        String timestamp = (String) rawPayload.getOrDefault("timestamp", java.time.Instant.now().toString());

        // ⚠️ 1. Enforce our structural system validation rules here
        if ("CRASH".equalsIgnoreCase(severity)) {
            throw new IllegalArgumentException("UNHANDLED TELECOM METRIC FAULT: Severity 'CRASH' is an illegal monitoring state!");
        }

        // 🔄 2. Map data fields seamlessly to our strict Avro Contract Builder
        AlarmTelemetryAvro avroRecord = AlarmTelemetryAvro.newBuilder()
                .setEquipmentId(equipmentId)
                .setSeverity(severity)
                .setProblem(problem)
                .setTimestamp(timestamp)
                .build();

        // 📤 3. Stream out binary payload using your properties-configured Confluent Serializer
        kafkaTemplate.send(PROD_TOPIC, avroRecord.getEquipmentId().toString(), avroRecord);
        log.info("🚀 Ingestion Bridge: Pristine binary Avro record safely flushed to core network log.");
    }
}