services:
  config-server:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app/config-server
    command: mvn spring-boot:run

  eureka-server:
    # Switched to a pristine, modern OpenJDK runtime that supports modern Docker engines perfectly
    image: eclipse-temurin:21-jre-alpine
    container_name: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - .:/app
    working_dir: /app/eureka-server
    # Executes the pre-compiled target JAR instantly without compiling or downloading Maven files!
    command: sh -c "sleep 30 && java -jar target/*.jar --spring.config.import=configserver:http://config-server:8888"
    depends_on:
      - config-server

  ticket-service-1:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: ticket-service-1
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    working_dir: /app/ticket-service
    command: bash -c "sleep 38 && mvn spring-boot:run -Dspring-boot.run.arguments='--server.port=8081 --eureka.instance.instance-id=ticket-service-1 --spring.config.import=configserver:http://config-server:8888 --eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/'"

  ticket-service-2:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: ticket-service-2
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    working_dir: /app/ticket-service
    command: bash -c "sleep 38 && mvn spring-boot:run -Dspring-boot.run.arguments='--server.port=8082 --eureka.instance.instance-id=ticket-service-2 --spring.config.import=configserver:http://config-server:8888 --eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/'"

  alarm-processor:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: alarm-processor
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app/alarm-processor
    command: bash -c "sleep 38 && mvn spring-boot:run -Dspring-boot.run.arguments='--spring.config.import=configserver:http://config-server:8888 --eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/'"
    
  gateway-service:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: gateway-service
    ports:
      - "8060:8060"
    volumes:
      - .:/app
    working_dir: /app/gateway-service
    # Giving it a 35-second sleep delay to let Eureka stabilize first
    command: bash -c "sleep 38 && mvn spring-boot:run -Dspring-boot.run.arguments='--spring.config.import=configserver:http://config-server:8888'"
    depends_on:
      - eureka-server
  
  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    ports:
      - "9411:9411"
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_URL=http://keycloak:8080
    ports:
      - "8083:8080"